[package]
name = "instruction-macros-traits"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
solana-address = { workspace = true, features = ["copy"] }
solana-program-error.workspace = true
